### ISSUE TITLE
Alias/NFT outputs included for no reason

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger-archive/iota.rs#1433]
If I create an alias or NFT, then use try and send tokens to said Alias or NFT address it will do two unexpected things:
- Return the n-1 transaction instead of the nth transaction.
- Include the Alias or NFT in all subsequent transactions

This returning n-1 transaction seems to persist until destroying and recreating the account manager

Example

Transaction 1 - Create Alias:
- Transaction: https://explorer.shimmer.network/testnet/transaction/0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad
- Returned: Correct transaction with id: 0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad

Transaction 2 - Send to Alias
- Transaction: https://explorer.shimmer.network/testnet/transaction/0xb751d64f5db265565ac9dcd43d6f9bb3b8d4175f1087febe8e19f39261930c14
- Returned: Previous Transaction with id: 0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad
- Includes my Alias for no reason?

Transaction 3 - Send to Mark’s Alias
- Transaction: https://explorer.shimmer.network/testnet/transaction/0xa75bf0324847f9e2c58a7308a32842eeb19ce5e31bae3e5e8d206bfa7ac2fd3f
- Returned: Previous Transaction with id: 0xb751d64f5db265565ac9dcd43d6f9bb3b8d4175f1087febe8e19f39261930c14
- Includes my Alias for no reason?

Also happens with NFTS

**Comment by Thoralf-M** [comment]
In the transaction 2 the alias might was included because its id was still the null id https://api.testnet.shimmer.network/api/core/v2/outputs/0x2b22a17006c2500d6725fbda269a6705f65d51c4b1389bbc0190b6e3032151ad0000
And in transaction 3 it was added to unlock the basic output which had an alias address in the unlock condition 
![image](https://user-images.githubusercontent.com/46689931/205039910-fc94bd4e-0de9-4173-9235-f52f34f78ba8.png)

**Comment by thibault-martinez** [comment]
Should be fixed by the new ISA.
