### ISSUE TITLE
Whats the point of a default nonce? Isnt setting an Option::None better? otherwise elsewhere we have to validate DEFAULT nonce vs block nonce again

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger-archive/iota.rs#1459]
Whats the point of a default nonce? Isnt setting an Option::None better? otherwise elsewhere we have to validate DEFAULT nonce vs block nonce again

_Originally posted by @kwek20 in https://github.com/iotaledger/iota.rs/pull/1346#discussion_r1053395511_

**Comment by Thoralf-M** [comment]
To me it looks fine how it's now, since 0 is used fore remote PoW
But changing it would also not require any big changes, I think we would just need to set it to 0 ourselves in this place https://github.com/iotaledger/iota.rs/blob/b6bfcfb179c6aedbbd59877bff1c1ba3ddb711ea/client/src/api/block_builder/pow.rs#L26-L32

Closing it for now, @kwek20 pls reopen if you want to do it anyways
