### ISSUE TITLE
Better handling of dust transactions

### ISSUE THREAD

**Issue by gdelazzari** [iotaledger-archive/iota.rs#465]
## Description

The input selection logic in https://github.com/iotaledger/iota.rs/blob/59da05593e4a16a4d11b219782828ed37c68c38c/iota-client/src/api/message_builder.rs#L174 should be smarter when there is an unspent dust allowance output along with some unspent outputs and a transaction is initiated that would produce dust.

For instance, if address B has
- a 1Mi dust allowance unspent output
- a 1Mi unspent output

and a transaction of 100i is initiated to address A (which of course must be in the right conditions for accepting dust) with a `MessageBuilder` as below:
```rust
let message = iota
    .message()
    .with_seed(seed_of_B)
    .with_output(A, 100)?
    .finish()
    .await?;
```
the current implementation ends up returning `DustError("No dust output allowed on address B")`, even if the transaction is possible by spending the second output in the list above.

## Motivation

Simpler usage of the library, i.e. users of the crate don't need to worry about implementing custom input selection logic when doing dust transactions.

## Requirements

I'm not sure about the exact requirements of the algorithm inside `finish_transaction()`, see "Description" for the wanted behavior.

## Are you planning to do it yourself in a pull request?

Maybe, if I can figure it out

**Comment by Thoralf-M** [comment]
Currently we get all outputs from an address and then just go through them one after the other
We could do two loops instead of one and only request signature locked outputs in the first loop and if that's not enough we do a second round with the dust allowance outputs added, that way we would select the dust outputs always first and when we select the dust allowance outputs there can't be dust anymore
But there could be edge cases where you have a lot dust outputs on multiple addresses and then it could fail if there are more than ~130 because we can only have 127 inputs and the balance would maybe not sufficient, but if we also include a dust allowance output that might work
To handle such cases we could also store all output metadata separated and if we reach the max inputs without having enough balance we could select better inputs from all available outputs, for example start adding the outputs with the largest amount and when we have enough dust outputs as input so we can also use a dust allowance output, then we also add it before we add more dust
