### ISSUE TITLE
Possibility to sign/process with private keys

### ISSUE THREAD

**Issue by dev0pa** [iotaledger-archive/iota.rs#762]
## Description

It should be possible to process individual private keys

## Motivation

one can create paperwallets (gift, etc.) and process them individually without compromising an entire seed. 

## Are you planning to do it yourself in a pull request?
no

**Comment by Thoralf-M** [comment]
We decided to not support individual private keys, because everything is build around a seed and we don't see use cases where individual private keys are really required.  Supporting private keys would require many changes and more maintenance for us, for paperwallets I would recommend to use mnemonics because they can also be imported in the Firefly wallet and if you fear compromising an entire mnemonic/seed you can just use multiple mnemonics
As alternative we have two libraries that support private keys https://github.com/iotaledger/iota.js and https://github.com/iotaledger/iota.go
