### ISSUE TITLE
[Task]: Add high level function to get inputs from a transaction/message

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#801]
## Description
Add high level function to get inputs from a transaction/message; __NOT__ just their ID, but the full output with an amount and address.

The typical data flow should look like...
1. Get transaction by transaction or message ID
2. Get outputs from the input IDs
3. Return the outputs

## Motivation
Many people want to know the inputs for different reasons and it should be easy to get them.

## Requirements
- [ ] Implement high-level function for retrieving inputs via transaction ID
- [ ] Implement high-level function for retrieving inputs via message ID

## Open questions (optional)
- Do we want to accept the message or transaction ID? (__answer__: transaction ID)

## Are you planning to do it yourself in a pull request?
No.

**Comment by maxwellmattryan** [comment]
I think the transaction ID would be better since it is closer in the domain to UTXOs / value transfer. Although I don't see why we couldn't have a `get_inputs_from_message` function that would use the underlying `get_inputs_from_transaction` function after some additional checks / logic. What do you think?

**Comment by Thoralf-M** [comment]
Sure, we can also add both

**Comment by samuel-rufi** [comment]
Implemented by https://github.com/iotaledger/iota.rs/pull/909
