### ISSUE TITLE
Cleanup Error enum

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#865]
## Description

Cleanup iota.rs Error enum

## Motivation

Currently the errors are more or less just added in some way, but there is no clear ordering and naming (some end with `Error`, others not like `NotEnoughBalance`)

## Open questions (optional)

How should it look? 

## Are you planning to do it yourself in a pull request?

No.

**Comment by jyhi** [comment]
I have a design of using only a few descriptive errors (e.g. `InvalidResponse`) carrying `dyn Error` trait objects, but that requires the function returning an error to box the error (and it requires a box, too). No automatic `From` conversion can happen, because there isn't an one-to-one mapping between errors from our dependencies to our own error variants. In the `Debug` display it also only shows that an `Error` is wrapped, e.g. `InvalidResponse(Error(...))`, as the type information would be lost.

```rust
    /// An invalid / malformed input was given by a user.
    #[error("invalid input: {0}")]
    InvalidInput(Box<dyn std::error::Error>),

    /// An invalid / malformed response was received from a node.
    #[error("invalid response received: {0}")]
    InvalidResponse(Box<dyn std::error::Error>),

    /// An computer network error (e.g. a loss of connection) happened.
    #[error("network error: {0}")]
    NetworkError(Box<dyn std::error::Error>),

    /// An error was returned by the node software.
    #[error("the node responded with an error: {code} {reason}")]
    NodeError { code: u16, reason: String },
```

https://github.com/lmy441900/atoi.rs/blob/master/src/types/error.rs

**Comment by jyhi** [comment]
For the naming, this guide may be helpful: https://rust-lang.github.io/api-guidelines/naming.html#names-use-a-consistent-word-order-c-word-order
